Feature/star 440
EscolaLMS/sdk pull request #118
Opened 2022-04-27 13:24 UTC by victazzz

2022-04-28 06:57 UTC, mtmotyka approved these changes

2022-04-29 12:18 UTC, qunabu requested changes

2022-04-29 12:18 UTC, qunabu commented on src/react/context/defaults.ts
> +    body: Partial<EscolaLms.Questionnaire.Models.QuestionAnswer>
https://escolalms.github.io/ts-models/modules/EscolaLms.Questionnaire.Http.Requests.html

2022-04-29 12:18 UTC, qunabu commented on src/react/context/defaults.ts
> +    body: Partial<EscolaLms.Questionnaire.Models.QuestionAnswer>
https://escolalms.github.io/ts-models/modules/EscolaLms.Questionnaire.Http.Requests.html

2022-05-04 05:49 UTC, merged