Add cartContext to list of all context
EscolaLMS/sdk pull request #262
Opened 2023-04-24 06:58 UTC by rudzky

2023-04-24 09:37 UTC, qunabu requested changes
please add type instead of `any`

2023-04-24 09:37 UTC, qunabu commented on src/services/cart.ts
> +  return request<API.DefaultResponse<any>>(`${apiUrl}/api/cart/products`, {
please add type instead of `any`

2023-04-24 12:12 UTC, rudzky commented on src/services/cart.ts
> +  return request<API.DefaultResponse<any>>(`${apiUrl}/api/cart/products`, {
waiting for ts-models update

2023-04-25 15:01 UTC, qunabu approved these changes

2023-04-25 15:03 UTC, merged